report_config:
  format: csv # csv, md or html
  s3_config:
    access_key: testy
    secret_key: testy
    region: us-east-1
    endpoint: http://10.3.8.31:80
    bucket: test
    skipSSLverify: true

global_config:
  ultra_large_scale: true # indicate ultra-large-scale task
  server_side_listing: true # Whether to list files on server side

  feishu_url: "feishu_url"
  fs_types:
    - yrfs_ec
  tasks_file: deploy/data_sources.txt

  file_list_dir: /mnt/yrfs/public-data/user/zhengliang/
  file_list_dir_fs_type: yrfs_ec
  max_files_per_output: 500000
  concurrency: 3

  # --checkers 128 --transfers 128 --size-only --local-no-set-modtime --log-level INFO --log-file
  rclone_flags:
    checkers: 64
    log_level: INFO
